version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@1.1.0
  aws-ecr: circleci/aws-ecr@6.8.0
  maven: circleci/maven@1.0.0

jobs:
  docker_build_and_push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - aws-ecr/build-image
          repo: $CIRCLE_PROJECT_REPONAME
          tag: $MAVEN_BUILD_VERSION
          extra_build_args: '--build-arg MAVEN_BUILD_NAME=$MAVEN_BUILD_NAME'
      - aws-ecr/build-image
          repo: $CIRCLE_PROJECT_REPONAME
          tag: latest
          extra_build_args: '--build-arg MAVEN_BUILD_NAME=$MAVEN_BUILD_NAME'
      - aws-ecr/push-image
        repo: $CIRCLE_PROJECT_REPONAME
        tag: $MAVEN_BUILD_VERSION,latest

workflows:
  build_test_release:
    jobs:
      - maven/test:
          post-steps:
            - persist_to_workspace:
                root: ./
                paths:
                  - target/classes/build-info.env
                  - target/*.jar
      - docker_build_and_push:
          requires:
            - maven/test
          pre-steps:
            - checkout
            - attach_workspace:
                at: ./
            - run: echo $(ls -la target)
            - run: echo 'source ./target/classes/build-info.env' >> $BASH_ENV
