version: 2.1

orbs:
  docker: circleci/docker@1.0.0
  maven: circleci/maven@1.0.0

workflows:
  build_test_release:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - docker/check-and-build-only
