version: 2.1

orbs:
  docker: circleci/docker@1.0.0
  maven: circleci/maven@1.0.0

jobs:
  docker_build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
          tag: '$CIRCLE_SHA1,latest'

workflows:
  build_test_release:
    jobs:
      - maven/test:
          post-steps:
            - persist_to_workspace:
                root: ./
                paths:
                  - target/*.jar
      - docker_build:
          requires:
            - maven/test
          pre-steps:
            - attach_workspace:
                at: /tmp/workspace
            - run: echo $(ls -la /tmp/workspace/target)
