version: 2.1

orbs:
  docker: circleci/docker@1.0.0
  maven: circleci/maven@1.0.0

jobs:
  docker_build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: $MAVEN_BUILD_VERSION
          extra_build_args: '--build-arg MAVEN_BUILD_NAME=$MAVEN_BUILD_NAME'
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: latest
          extra_build_args: '--build-arg MAVEN_BUILD_NAME=$MAVEN_BUILD_NAME'
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: $MAVEN_BUILD_VERSION,latest

workflows:
  build_test_release:
    jobs:
      - maven/test:
          post-steps:
            - persist_to_workspace:
                root: ./
                paths:
                  - target/classes/build-info.env
                  - target/*.jar
      - docker_build:
          requires:
            - maven/test
          pre-steps:
            - checkout
            - attach_workspace:
                at: ./
            - run: echo $(ls -la target)
            - run: echo 'source ./target/classes/build-info.env' >> $BASH_ENV
